name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    services:
      # Label used to reference the service container
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rails_test
        ports:
          # Maps the container's port 5432 to the host's port 5432
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2 # Pick a Ruby version.  This should match your .ruby-version
          bundler-cache: true # runs bundle install and caches
      - name: Install PostgreSQL Client
        run: sudo apt-get install libpq-dev
      - name: Create database.yml
        run: |
          mkdir -p config
          cat > config/database.yml <<EOF
          development:
            adapter: postgresql
            encoding: unicode
            database: rails_test
            username: rails
            password: password
            host: localhost
          test:
            adapter: postgresql
            encoding: unicode
            database: rails_test
            username: rails
            password: password
            host: localhost
          EOF
      - name: Set up database
        run: |
          bin/rails db:environment:set RAILS_ENV=test
          bin/rails db:create
          bin/rails db:setup
          bin/rails db:test:prepare
      - name: Run rspec
        run: bin/rspec

    # services:
    #  redis:
    #    image: redis
    #    ports:
    #      - 6379:6379
    #    options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
#    steps:
#      - name: Install packages
#        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git pkg-config
#
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: .ruby-version
#          bundler-cache: true
#
#      - name: Run tests
#        env:
#          RAILS_ENV: test
#          # REDIS_URL: redis://localhost:6379/0
#        run: bin/rails db:test:prepare test
